### PR TITLE
Addition of goods struct

### PR DESCRIPTION
**Pull request by ClarkeCode**
Also fixed typo present in `goods.json`

### CODE REVIEW

**Review by Hop311 — COMMENTED** [review]
Looks *Good*, two small comments:
- It'll need a default move constructor before it can go in a Registry:
```c++
Good(Good&&) = default;
```
- Colour will be parsed into a 24-bit RGB int (so stored in a `uint32_t`), similar to `Province::colour_t`, so might be worth moving the alias to `OpenVic2::colour_t` in `Types.hpp`, as well as moving helper functions like `colour_to_hex_string`.

**Comment by ClarkeCode** [comment]
***Good*** idea, next commit coming shortly :)

**Comment by Spartan322** [comment]
> `Merge branch 'main' of github.com:OpenVic2Project/OpenVic2 into goods`

Please use a rebase over a merge, this is very likely to cause a really stupid merge conflict again.

**Review by Hop311 — APPROVED** [review]

**Review by Hop311 — APPROVED** [review]
(assuming this passes all the tests)

**Comment by Spartan322** [comment]
**WHY WAS THIS MERGED?**

**Pull request merged**
