### PR TITLE
Fix Credits to use theme type variants over LabelSettings

### PR DESCRIPTION
**Pull request by Spartan322**
Remove LabelSettings resources from Credits
Moved theme load from MainMenu to GameMenu scene
Removed Button references from default_theme resource

This enables reliable theme application

### CODE REVIEW

**Review by Orwellian-225 — DISMISSED** [review]
Looks good, not exactly sure what you did but it didn't break anything I did so its good enough for me

**Comment by Spartan322** [comment]
> Looks good, not exactly sure what you did but it didn't break anything I did so its good enough for me

What this accomplishes is removes the reliance on LabelSettings and sticks everything in the default_theme, also cleans up the default theme.

**Comment by Orwellian-225** [comment]
> What this accomplishes is removes the reliance on LabelSettings and sticks everything in the default_theme, also cleans up the default theme.

Ahh yes ok. That makes sense, moving it into the default theme is probably a smarter thing to do. I was unaware you could do that, as I was under the impression you needed to add new themes or at least new resources

**Review by Orwellian-225 — DISMISSED** [review]

**Review by BrickPi — APPROVED** [review]

**Comment by Spartan322** [comment]
Sorry I keep noticing when approved that there is some problem I left in this PR that needs to be reverted.

**Review by Orwellian-225 — APPROVED** [review]
Still looks good

**Pull request merged**
