### PR TITLE
Add automated Git release info retrieval on export

### PR DESCRIPTION
**Pull request by Spartan322**
Add commit hash label to MainMenu
Add click-copyable tag, commit hash, and checksum to main menu Rename VersionChecksumBox to ReleaseInfoBox
Move ReleaseInfoBox to separate scene and script
Add GIT_INFO.gd for generic project running
Add openvic2-plugin addon for handling export plugin

### CODE REVIEW

**Comment by Spartan322** [comment]
This seems to be reporting the wrong git commit.

**Comment by Spartan322** [comment]
This should properly identify the respective commit for the project at all times, same as how Godot does it in their repository, however I'll wait for the build to finish to validate this.

**Comment by Spartan322** [comment]
The workflow can probably be made simpler, probably using our own homebrew actions. Regardless I have confirmed this does work properly now.

**Review by Hop311 — APPROVED** [review]
LGTM

**Comment by Spartan322** [comment]
I think I'm gonna try and make the workflow better, so don't merge this PR.

**Review by ClarkeCode — APPROVED** [review]
Looks great!

**Pull request merged**
